Imu and odom fusion
luxonis/rae-ros pull request #52
Opened 2023-11-02 10:02 UTC by AnielAlexa

2023-11-02 14:09 UTC, sskorol commented
@AnielAlexa hi, could you please record a short video of these IMU changes in RViz? Because I've already tried to apply some of your changes related to ekf and it didn't work for me.

2023-11-02 14:23 UTC, AnielAlexa commented
@sskorol Here is a short video with IMU fusion while is performing a 1x1 m square.  These days probably will be available an image using data from internal fusion of IMU, which seems more stable. 
[Screencast from 10-20-2023 04:05:43 PM.webm](https://github.com/luxonis/rae-ros/assets/139551403/4aaaa889-289e-427d-8385-6b8e0c31d5a1)

2023-11-02 15:23 UTC, sskorol commented
@AnielAlexa which launch script are you using in Docker container?

2023-11-03 07:02 UTC, AnielAlexa commented
@sskorol you can try this with `ros2 launch rae_bringup robot.launch.py`. I do not test SLAM yet with this change, but will come soon.

2023-11-03 07:05 UTC, sskorol commented
Yup, when I said it didn't work correctly, I meant SLAM scenario. Looking forward.

2023-11-03 07:13 UTC, AnielAlexa commented
Yeah, SLAM do not work correctly. If want and have time, you can record a video like my one. I'm curious how perform your RAE.

2023-11-06 17:23 UTC, Serafadam requested changes

2023-11-06 17:23 UTC, Serafadam commented on rae_hw/src/rae_motors.cpp
> +
Please reformat whitespaces in this file

2023-11-06 17:23 UTC, Serafadam commented on rae_camera/config/camera.yaml
> +      i_acc_freq: 65
Frequency for acceleration should be higher, did you try it with other paramers?

2023-11-06 19:08 UTC, AnielAlexa commented on rae_camera/config/camera.yaml
> +      i_acc_freq: 65
I tried various combination with condition i_gyro_freq > i_acc_freq. I didn't notice a big difference. It is set now at 65 Hz because EKF also work at 50 Hz (If i set i_acc_freq: 50 it gives under sometimes). This is more or less PoC.

2023-11-28 10:32 UTC, merged